### ISSUE TITLE
Swagger ui problem

### ISSUE THREAD

**Issue by Julian-Louis** [pierreminiggio/api.touslesverbes.com#5]
Hello my @pierreminiggio 
It seems like the api documentation of api.touslesverbes.com is broken:
![image](https://user-images.githubusercontent.com/86676740/139131511-128c5e4a-cdeb-4a64-8020-043fd7738e3d.png)

**Comment by pierreminiggio** [comment]
Ué c'est cassé depuis plusieurs mois, mais j'ai jamais pris le temps de comprendre pourquoi. Flemme xD
